
/**
 * The parsed model data structure.
 *
 * Currently this is a `Map` representing the model data in its entirety,
 * generated ahead of time via the {@link useModelData} hook. This may
 * change to a structure where the points, domains etc. are generated by
 * the visualisation component in the future.
 */
export interface ModelData extends Map<string, any> {
  /** Hierarchical lookup: location -> variant -> site data. */
  get(key: 'points'): Map<string, Map<string, Map<string, any>>>; // todo: type inner point data
  /** Model-defined variants (`modelJson.metadata.variants`). */
  get(key: 'variants'): string[];
  /** Sorted `YYYY-MM-DD` strings, guaranteed dense (no holes). Bridges `metadata.dates` and `metadata.forecast_dates`. */
  get(key: 'dates'): string[];
  /** Model-defined locations (`modelJson.metadata.location`). */
  get(key: 'locations'): string[];
  /** Lookup: date string -> index in `dates`. */
  get(key: 'dateIdx'): Map<string, number>;
  /** Whether the date array is sparse (not every day represented). */
  get(key: 'sparseDates'): boolean;
  /** Provided via `DatasetConfig`. Defaults applied otherwise. Maps variant name to CSS color string. */
  get(key: 'variantColors'): Map<string, string>;
  /** Provided via `DatasetConfig`. Falls back to variant keys. Maps variant name to display label. */
  get(key: 'variantDisplayNames'): Map<string, string>;
  /** `metadata.pivot` if present, else the final entry in variants. */
  get(key: 'pivot'): string;
  /** Crossover date between nowcasting and forecasting. */
  get(key: 'nowcastFinalDate'): string;
  /** `metadata.updated` if present. */
  get(key: 'updated'): string | undefined;
  /** Per-site `[min, max]` for non-temporal sites (e.g. growth advantage). */
  get(key: 'domains'): Map<string, [number, number]>;
  /** Set of site keys discovered during data processing (e.g. 'freq', 'ga', 'freq_raw'). */
  get(key: 'sites'): Set<string | undefined>;
  /** Encode a hierarchy of locations for filtering. Category -> value -> list of locations. */
  get(key: 'locationHierarchy'): Map<string, Map<string, string[]>> | undefined;
}
