
/**
 * The parsed model data structure.
 *
 * Currently this is a `Map` representing the model data in its entirety,
 * generated ahead of time via the {@link useModelData} hook. This may
 * change to a structure where the points, domains etc. are generated by
 * the visualisation component in the future.
 */
export interface ModelData extends Map<string, any> {
  /** TODO XXX */
  get(key: 'config'): ModelDataConfig;
  /** Hierarchical lookup: location -> variant -> site data. */
  get(key: 'points'): Points;
  /** Model-defined variants (`modelJson.metadata.variants`). */
  get(key: 'variants'): string[];
  /** Sorted `YYYY-MM-DD` strings, guaranteed dense (no holes). Bridges `metadata.dates` and `metadata.forecast_dates`. */
  get(key: 'dates'): string[];
  /** Model-defined locations (`modelJson.metadata.location`). */
  get(key: 'locations'): string[];
  /** Lookup: date string -> index in `dates`. */
  get(key: 'dateIdx'): Map<string, number>;
  /** Whether the date array is sparse (not every day represented). */
  get(key: 'sparseDates'): boolean;
  /** Provided via `DatasetConfig`. Defaults applied otherwise. Maps variant name to CSS color string. */
  get(key: 'variantColors'): Map<string, string>;
  /** Provided via `DatasetConfig`. Falls back to variant keys. Maps variant name to display label. */
  get(key: 'variantDisplayNames'): Map<string, string>;
  /** `metadata.pivot` if present, else the final entry in variants. */
  get(key: 'pivot'): string;
  /** Crossover date between nowcasting and forecasting. */
  get(key: 'nowcastFinalDate'): string;
  /** `metadata.updated` if present. */
  get(key: 'updated'): string | undefined;
  /** Per-site `[min, max]` for non-temporal sites (e.g. growth advantage). */
  get(key: 'domains'): Record<string, [number, number]>;
  /** Encode a hierarchy of locations for filtering. Category -> value -> list of locations. */
  get(key: 'locationHierarchy'): Map<string, Map<string, string[]>> | undefined;
}

export interface ModelDataConfig {
  /** Information about the sites */
  sitesInfo: {
    freq: {
      /** site values which contain the model estimate values */
      estimateSites: string[];
      /** ps value to use as the model estimate value for estimateSites */
      ps_point_estimator: string;
      /** ps values to use as the model estimate intervals (HPD/HPI/CI etc) */
      ps_interval_estimator?: [string, string];
      /** display name of the interval */
      interval_name: string;
      /** site value for raw measurements */
      raw_site: string;
      /** name to display for the `raw_site` data */
      raw_name: string;
      /** site value for smoothed measurements */
      smoothed_site: string;
      /** name to display for the `raw_site` data */
      smoothed_name: string;
    };
    ga: {
      /** ps value to use as the model estimate value for estimateSites */
      ps_point_estimator: string;
      /** ps values to use as the model estimate intervals (HPD/HPI/CI etc) */
      ps_interval_estimator?: [string, string];
      /** display name of the interval */
      interval_name: string;
    };
    /** TODO XXX RENAME */
    relativeGA: {
      /** Compute popGA and relativeGA at parse time. Needed to plot certain graphs. */
      enable: boolean;
    };
  }
}

type variant = string;
/** variant name */

type location = string;
/** location name */

export interface GenericTimePoint {
  date: string;
  value?: number;
}

export interface FreqTimePoint extends GenericTimePoint {
  lower?: number;
  upper?: number;
  raw?: number;
  smoothed?: number;
}

export interface FreqGaTimePoint {
  date: string;
  /** frequency (NOT logit transformed) */
  freq: number;
  /** log(variant weighted ga) - log(pop ga) TODO XXX */
  relativeGa: number;
}

export interface FreqData {
  temporal: (FreqTimePoint | undefined)[];
}

export interface RelativeGAData {
  temporal: (GenericTimePoint | undefined)[];
}

export interface popGAData {
  temporal: (GenericTimePoint | undefined)[];
}

export interface FreqGAData {
  temporal: (FreqGaTimePoint | undefined)[];
}

export interface MeanPopFitnessData {
  temporal: GenericTimePoint[];
  lower: number;
  upper: number;
}

interface RelativeFitnessData {
  temporal: GenericTimePoint[];
}

export interface GaData {
  value?: number;
  lower?: number;
  upper?: number;
}

export interface Points {
  freq?: Record<location, Record<variant, FreqData>>;
  ga?: Record<location, Record<variant, GaData>>;

  /** Mean population fitness is the sum of freq_i(t) * ga_i for all variants i */
  meanPopFitness?: Record<location, MeanPopFitnessData>;

  /** Relative Fitness is the variant's GA / meanPopFitness.
   * (The fraction is log-transformed)
   */
  relativeFitness?: Record<location, Record<variant, RelativeFitnessData>>;
  
  // TODO XXX RENAME to
  relativeGA?: Record<string, Record<string, RelativeGAData>>;
  /** mean population fitness: <location> → temporal values */
  // TODO XXX RENAME! meanPopFit
  popGA?: Record<string, popGAData>;
  // TODO XXX rENAME: 
  freqGA?: Record<string, Record<string, FreqGAData>>;
}
