import { max, schemeTableau10 } from 'd3';

/**
 * Maps used instead of object as it's (seemingly) faster + consumes less
 * memory (https://www.zhenghao.io/posts/object-vs-map)
 * @private
 */


const THRESHOLD_FREQ = 0.005; /* half a percent */
const INITIAL_DAY_CUTOFF = 10; /* cut off first 10 days */

const DEFAULT_SITES = {
  // Future options: specify the ps values to use, whether to use `${key}_forecast` etc
  ga: {
    temporal: false,
  },
  I_smooth: {
    temporal: true,
    stacked: true,
  },
  freq: {
    temporal: true,
    raw: 'daily_raw_freq',
    smoothed: 'weekly_raw_freq',
  },
}

/**
 * @typedef {Map} ModelData
 * Currently this Map represents the model data in its entirety and
 * is generated ahead of time via the `useModelData` hook. This may change
 * to a structure where the points, domains etc are generated by the
 * visualisation component in the future. See NOTES.md for more.
 * @property {Points} points
 * @property {Array} variants modelJson.metadata.variants
 * @property {Array} dates sorted array of YYYY-MM-DD dates, guaranteed not to have any holes.
 *                         These dates bridge both `modelJson.metadata.dates` and `modelJson.metadata.forecast_dates`.
 * @property {Array} locations modelJson.metadata.location
 * @property {Map} dateIdx lookup for date string -> idx in dates array
 * @property {Map} variantColors provided via `DatasetConfig`. Overrides data set in the JSON. Default colors set if not provided.
 * @property {Map} variantDisplayNames provided via `DatasetConfig`. Overrides data set in the JSON. Keys used if not provided.
 * @property {String} pivot modelJson.metadata.pivot if available, else final entry in the model's list of variants
 * @property {string} nowcastFinalDate
 * @property {string} updated
 * @property {Object} domains
 *
 * @inner
 * @memberof module:@nextstrain/evofr-viz
 */

/**
 * @returns {ModelData}
 * @private
 * @throws Error
 */
export const parseModelData = (modelName, modelJson, configSites, configProvidedVariantColors, configProvidedVariantDisplayNames) => {
  if (!modelName) modelName="Unknown";
  console.log(`${modelName} - parsing model data`)

  /** SITES - which keys to parse from model (and how to parse them) */
  const sitesInfo = collectSites(modelJson.metadata.sites, configSites);

  /** DATES */
  const [dates, updated, nowcastFinalDate, dateSummary, sparseDates] = extractDatesFromModels(modelJson)
  const dateIdx = new Map(dates.map((d, i) => [d, i]));

  /** VARIANTS - e.g. clades, lineages etc. pivot will be first element */
  const {variants, pivot} = extractVariants(modelJson)

  const data = new Map([
    ["locations", modelJson.metadata.location],
    ["variants", variants],
    ["dates", dates],
    ["dateIdx", dateIdx],
    ["sparseDates", sparseDates],
    ["updated", updated],
    ["nowcastFinalDate", nowcastFinalDate],
    ["points", undefined],
    ["domains", undefined],
    ["sites", undefined], /* sites discovered in processModelData */
    ["pivot", pivot],
    ['domains', new Map([])],
    ["variantColors", getVariantColors(modelJson, variants, configProvidedVariantColors)],
    ["variantDisplayNames", variantDisplayNames(modelJson, variants, configProvidedVariantDisplayNames)],
  ]);
  
  console.log(`\t${data.get('locations').length} locations x ${data.get('variants').length} variants x ${dates.length} dates`)
  console.log("\t"+dateSummary);

  /** POINTS hold all the actual data for plotting in a hierarchical Map structure.
   * We initialise to the following structure:
   * 
   * points → <location> → <variant> → "variant" → <variant>
   *                                 → "temporal" → temporalArray
   *                                              → [idx] → "date" → YYYY-MM-DD || undefined
   *
   * Note: temporal[idx] corresponds to dates[idx]
   * We then add data dependent on the JSON contents, e.g. growth advantage sites add:
   * 
   * points → <location> → <variant> → "ga" → float
   *                                 → "ga_HDI_95_lower" → float
   *                                 → "ga_HDI_95_upper" → float
   *
   * and frequencies add:
   * 
   * points → <location> → <variant> → "temporal" → [idx] → "freq" → float[idx]
   *                                                      → "freq_HDI_95_lower" → float[idx]
   *                                                      → "freq_HDI_95_upper" → float[idx]
   */


  const points = initialisePoints(data.get('locations'), variants, dates)
  const ps_point_estimator = modelJson.metadata.ps_point_estimator || "median";

  const sites = processModelData(modelJson.data, points, dateIdx, sitesInfo, ps_point_estimator);
  data.set("sites", sites)
  
  /* Once everything's been added (including frequencies) - iterate over each point & censor certain frequencies */
  if (sitesInfo['freq']) {
    const {nanCount, censorCount} = censorTimePoints(points);
    console.log(`\t${censorCount} censored points as frequency<${THRESHOLD_FREQ}`);
    console.log(`\t${nanCount} points missing`);
  } else {
    console.warn(`Frequencies were not parsed from the model, no censoring of time points has occurred. Model results which had freq<${THRESHOLD_FREQ} may be unreliable.`)
  }

  /** compute stacked coordinates as needed */
  Object.entries(sitesInfo).filter(([site, info]) => info.stacked===true)
    .forEach(([site, _info]) => {
      computeStackedPoints(points, dates, site)
    });

  /** Compute domains for point estimates */
  Object.entries(sitesInfo).filter(([site, info]) => info.temporal===false)
    .forEach(([site, info]) => {
      data.get('domains').set(site, computeBounds(points, site));
    });

  data.set("points", points);

  console.log("DATA", data)
  return data;
};

function collectSites(modelSites, configSites) {
  let sitesInfo = {...DEFAULT_SITES};

  if (configSites) {
    if (typeof configSites !== 'object') {
      throw new Error(`The config-defined 'sites' has changed to an object (you have provided a ${typeof configSites})`)
    }
    sitesInfo = {...sitesInfo, ...configSites};
    console.log("Merged config-defined sites with defaults. Combined sites:", sitesInfo);
  }

  // Prune out any sites not in the model JSON
  for (const s of Object.keys(sitesInfo)) {
    if (!modelSites.includes(s)) {
      delete sitesInfo[s];
    }
  }

  return sitesInfo;
}

/**
 * @private
 */
function extractDatesFromModels(modelJson) {
  const jsonDates = (modelJson.metadata.dates || []).sort(); // YYYY-MM-DD are sorted correctly
  const jsonDatesForecast = (modelJson.metadata.forecast_dates || []).sort();

  /**
   * If dates are sparse, then we use them as-is, however if the dates are not sparse we create an array ourselves
   * so that all dates in the period are included. This affects how lines are drawn, as we will not draw lines (and CIs)
   * over "holes" in the dates array.
   */
  const sparse = Object.hasOwn(modelJson.metadata, "sparseDates") ?
    modelJson.metadata.sparseDates :
    sparseDates(jsonDates);
  const dates = sparse ?
    [...jsonDates, ...jsonDatesForecast] : 
    datesArray(jsonDates[0], max([jsonDates[jsonDates.length-1], jsonDatesForecast[jsonDatesForecast.length-1]]));

  /* The forecast date is simply the crossover date between now-casting and forecasting. It's not that simple -- from
  Marlin: "There’s really two different lines that should be there, but I would start with the date of the model run I think."
  */
  const updated = modelJson.metadata?.updated;
  let nowcastFinalDate;
  let updatedMsg = '';
  if (updated) {
    nowcastFinalDate = updated;
    updatedMsg = `Forecast starts at ${nowcastFinalDate} (via model update date).`
  } else {
    nowcastFinalDate = jsonDates[jsonDates.length-1];
    updatedMsg = `Forecast starts at ${nowcastFinalDate} (final entry in 'dates').`;
  }

  /* If we don't have sparse dates then skip initial days of model estimates to avoid artifacts in plots */
  let keepDates, summary;
  if (sparse) {
    keepDates = dates;
    summary = `Provided dates are sparse - there are ${keepDates.length} measurements which span the date range ${keepDates[0]} - ${keepDates[keepDates.length-1]}. ${updatedMsg}`;
  } else {
    keepDates = dates.slice(INITIAL_DAY_CUTOFF);
    summary = `Dates are not sparse, so the earliest ${INITIAL_DAY_CUTOFF} days have been ignored.`;
    summary += `\n\tDates now span ${keepDates[0]} - ${keepDates[keepDates.length-1]} (${keepDates.length} days). ${updatedMsg}`;
  }
  return [keepDates, updated, nowcastFinalDate, summary, sparse];
}

export function datesArray(startDate, endDate) {
  const dates = [];
  // start at noon so that as we enter/exit daylight savings, the +/- 1 hour change doesn't
  // change the day. See src/tests/date-parsing.js for more details
  let d = new Date(`${startDate}T12:00:00Z`);
  while (d.toISOString().split('T')[0] <= endDate) {
    dates.push(d.toISOString().split('T')[0])
    d.setDate(d.getDate()+1);
  }
  return dates
}


/**
 * Use a heuristic to check if the dates are sparse
 * If over 80% of the dates are subsequent (i.e. date[x+1] = date[x] + 1 day)
 * then the data is _not_ sparse.
 * @private
 */
function sparseDates(dates) {
  const n = dates.length;
  const objects = dates.map((d) => new Date(d));
  const msPerDay = 1000 * 60 * 60 * 24;
  const proportionSingleDaySpacing = objects.map((d, i) => {
    if (i===0) return 0;
    return Math.round((d - objects[i-1])/msPerDay);
  }).filter((gap) => gap===1).length / n;
  return proportionSingleDaySpacing < 0.8; 
}


/**
 * @private
 */
function extractVariants(modelJson) {
  // Reorder variants so that the pivot is first for all displays
  const variants = [...modelJson.metadata.variants];
  // Use the explicit pivot in the metadata if available, otherwise assume the
  // pivot is the last variant in the array
  const pivot = modelJson.metadata.pivot || variants[variants.length - 1];
  const pivotIndex = variants.indexOf(pivot);
  if (pivotIndex >= 0) {
    variants.splice(pivotIndex, 1);
    variants.unshift(pivot);
  }
  return {variants, pivot};
}

/**
 * @private
 */
function variantDisplayNames(modelJson, variants, configProvidedVariantDisplayNames) {
  if (configProvidedVariantDisplayNames) {
    return configProvidedVariantDisplayNames;
  }
  if (Array.isArray(modelJson.metadata?.variantDisplayNames)) {
    return new Map(modelJson.metadata.variantDisplayNames);
  }
  return new Map(variants.map((name) => [name, name]));
}

/**
 * @private
 */
function getVariantColors(modelJson, variants, configProvidedVariantColors) {
  let variantColors;
  if (configProvidedVariantColors) {
    variantColors = configProvidedVariantColors;
  } else if (Array.isArray(modelJson.metadata?.variantColors)) {
    variantColors = new Map(modelJson.metadata.variantColors);
  } else {
    // Todo - sample from a continuous scale when we have more than 10 variants
    // (e.g. collapsed pango lineages will have lots more!)
    variantColors = new Map(variants.map((name, idx) => [name, schemeTableau10[idx % 10]]));
  }
  
  const missingColors = variants.filter((v) => !variantColors.has(v));
  if (missingColors.length) {
    console.error(
      `Missing colors for ${missingColors.length} variant(s): ${missingColors.join(', ')}\n\n` +
      `All variants should have colors defined in metadata.variantColors.\n` +
      `(Grey will be used for these missing variants as a fallback)`
    );
    for (const v of missingColors) {
      variantColors.set(v, '#bdbdbd')
    }
  }

  return variantColors;
}

/**
 * Returns a TimePoint - a Map with a key of 'date' and the value
 * set to the *date* argument.
 */
function timePoint(date=undefined) {
  return new Map([
    ['date', date],
  ]);
}

function initialisePoints(locations, variants, dates) {
  return new Map(
    locations.map((location) => [
      location,
      new Map(
        variants.map((variant) => [
          variant,
          new Map([
            ['variant', variant],
            ['temporal', dates.map(timePoint)]
          ])
        ])
      )
    ])
  )
}

function computeBounds(points, key) {
  let _min = 100;
  let _max = 0;
  const keyLower = `${key}_HDI_95_lower`;
  const keyUpper = `${key}_HDI_95_upper`;
  for (const variantMap of points.values()) {
    for (const variantPoint of variantMap.values()) {
      if (variantPoint.get(keyLower)<_min) {
        _min = variantPoint.get(keyLower);
      } else if (variantPoint.get(keyUpper)>_max) {
        _max = variantPoint.get(keyUpper)
      }
    } 
  }
  return [_min,_max];
}

function censorTimePoints(points) {
  let [nanCount, censorCount] = [0, 0];
  /**
   * for any timePoint where the frequency is either not provided (NaN) or
   * under our threshold, we don't want to use any model output for this date
   * (for the given variant, location))
   */
  const censor = (point, idx, dateList) => {
    const freq = point.get('freq');
    if (isNaN(freq)) {
      dateList[idx] = timePoint();
      nanCount++;
    } else if (freq<THRESHOLD_FREQ) {
      dateList[idx] = timePoint();
      censorCount++;
    }
  }
  for (const variantMap of points.values()) {
    for (const variantPoint of variantMap.values()) {
      const dateList = variantPoint.get('temporal');
      dateList.forEach(censor)
    }
  }
  return {nanCount, censorCount};
}

/**
 * The *key* must already be set within points (and be temporal)
 * This will add ${key}_y0 and ${key}_y1 values with the stacking order determined
 * by the variant order
 */
function computeStackedPoints(points, dates, key) {
  for (const variantMap of points.values()) {
    let runningTotalPerDay = new Array(dates.length).fill(0);
    for (const variantPoint of variantMap.values()) {
      const dateList = variantPoint.get('temporal');
      dateList.forEach((point, idx) => {
        point.set(`${key}_y0`, runningTotalPerDay[idx]);
        runningTotalPerDay[idx] += point.get(key) || 0; // may be NaN
        point.set(`${key}_y1`, runningTotalPerDay[idx]);
      })
    }
  }
}

/**
 * Dynamically add points to the data store by looping over the JSON data elements
 * The dynamic nature comes from the user being able to select what fields
 * are parsed and how they should be parsed.
 */
function processModelData(data, points, dateIdx, sitesInfo, ps_point_estimator) {
  const keysAdded = new Set();
  const keyInfo = {};
  const lookup = {};

  for (const [siteName, siteInfo] of Object.entries(sitesInfo)) {
    keyInfo[siteName] = siteInfo;
    lookup[siteName] = defaultGetter(siteName);
    if (siteInfo.raw) {
      keyInfo[siteInfo.raw] = siteInfo;
      lookup[siteInfo.raw] = simpleGetter('freq_raw');
    }
    if (siteInfo.smoothed) {
      keyInfo[siteInfo.smoothed] = siteInfo;
      lookup[siteInfo.smoothed] = simpleGetter('freq_smoothed');
    }
  }

  function defaultGetter(baseKey) {
    return (store, d) => {
      const key = d.ps===ps_point_estimator ? baseKey
        : d.ps==="HDI_95_lower" ? `${baseKey}_HDI_95_lower`
        : d.ps==="HDI_95_upper" ? `${baseKey}_HDI_95_upper`
        : undefined;
      if (!key) return;
      store.set(key, d.value);
      return key;
    }
  }

  function simpleGetter(baseKey) { // doesn't consider the ps value
    return (store, d) => {
      store.set(baseKey, d.value);
      return baseKey;
    }
  }

  const lookupKeys = new Set(Object.keys(lookup));

  for (const d of data) {
    /* The site in the JSON isn't necessarily the key we store data under as we don't store forecasts under a different key */
    // TODO - allow the sitesInfo to enable this via `useForecast` boolean
    const key = d.site.replace("_forecast", "");

    if (lookupKeys.has(key)) {
      if (keyInfo[key].temporal === true && dateIdx.get(d.date) === undefined) continue;
      
      // Check if location and variant exist in metadata
      const locationMap = points.get(d.location);
      if (!locationMap) {
        console.error(`ERROR at data point: Location "${d.location}" not found in metadata.location`);
        console.error(`Available locations: ${Array.from(points.keys()).join(', ')}`);
        console.error(`Problematic data point:`, d);
        throw new Error(`Location "${d.location}" in data not found in metadata.location. Available locations: ${Array.from(points.keys()).join(', ')}`);
      }

      const variantPoint = locationMap.get(d.variant);
      if (!variantPoint) {
        console.error(`ERROR at data point: Variant "${d.variant}" not found in metadata.variants`);
        console.error(`Available variants: ${Array.from(locationMap.keys()).join(', ')}`);
        console.error(`Problematic data point:`, d);
        throw new Error(`Variant "${d.variant}" in data not found in metadata.variants. Available variants: ${Array.from(locationMap.keys()).join(', ')}`);
      }
      
      const store = keyInfo[key].temporal === true ?
        variantPoint.get('temporal')[dateIdx.get(d.date)] :
        variantPoint;

      const storeKey = lookup[key](store, d);
      keysAdded.add(storeKey);
    }      
  }
  return keysAdded;
}
